// Search-page copy is separate from app controls because it is also rendered at build time.
const pages = [
  {
    locale: "en", name: "English", path: "/positive-news", heading: "Positive news from around the world",
    description: "Find positive news and uplifting stories with BrightNews. Explore progress in science, health, nature and communities, with links to original reporting.",
    open: "Read the news", android: "Get the Android app", languages: "Read in your language",
    intro: "A balanced view of the world includes the things that are getting better. BrightNews brings together constructive reporting from multiple publishers so you can discover good news without searching through an entire news feed.",
    topicsTitle: "Good news worth following",
    topics: ["Science and health: discoveries, treatments and research that can improve lives.", "Nature and the planet: conservation, restoration and practical environmental solutions.", "People and communities: kindness, local initiatives and achievements that help others.", "Technology and innovation: useful ideas and tools that address real problems."],
    selectionTitle: "How we select stories",
    selection: "BrightNews collects articles from RSS feeds and news APIs, removes duplicates and uses topic filters and AI-assisted review to identify constructive stories. This process can make mistakes. Every summary links to the original reporting so you can check the details and context.",
    balance: "Positive news does not mean ignoring difficult events or claiming that every problem has been solved. Our aim is to add perspective with examples of progress, not replace wider news coverage.",
    faqTitle: "Questions about BrightNews",
    faq: [["Is BrightNews the original publisher?", "No. BrightNews is an independent news aggregator. Publishers remain the sources of the reporting; follow each story's source link to read the full article."], ["Are all articles translated?", "No. The app interface is available in several languages, but articles and summaries may remain in their source language. Use the language, country and topic filters to find relevant stories."], ["Can I read on my phone?", "Yes. BrightNews works in a web browser and is also available as an Android app. You can browse stories and save them to return to later."]],
    footer: "An independent project for a more balanced view of the news.",
  },
  {
    locale: "hr", name: "Hrvatski", path: "/pozitivne-vijesti", heading: "Pozitivne vijesti iz cijelog svijeta",
    description: "Otkrijte pozitivne vijesti i dobre priče uz BrightNews. Pratite napredak u znanosti, zdravlju, prirodi i zajednici, uz poveznice na izvorne članke.",
    open: "Čitajte vijesti", android: "Preuzmite Android aplikaciju", languages: "Čitajte na svojem jeziku",
    intro: "Uravnotežena slika svijeta uključuje i ono što se mijenja nabolje. BrightNews okuplja konstruktivne vijesti različitih medija kako biste lakše pronašli dobre vijesti, inspirativne priče i primjere stvarnog napretka.",
    topicsTitle: "Dobre vijesti koje vrijedi pratiti",
    topics: ["Znanost i zdravlje: otkrića, liječenja i istraživanja koja mogu poboljšati život.", "Priroda i planet: očuvanje okoliša, obnova prirode i praktična održiva rješenja.", "Ljudi i zajednica: solidarnost, lokalne inicijative i uspjesi koji pomažu drugima.", "Tehnologija i inovacije: korisne ideje i alati za rješavanje stvarnih problema."],
    selectionTitle: "Kako biramo vijesti",
    selection: "BrightNews prikuplja članke putem RSS izvora i novinskih API-ja, uklanja duplikate te uz tematske filtre i pomoć umjetne inteligencije prepoznaje konstruktivne priče. Postupak može pogriješiti. Svaki sažetak vodi na izvorni članak kako biste mogli provjeriti pojedinosti i kontekst.",
    balance: "Pozitivne vijesti ne znače zanemarivanje teških događaja niti tvrdnju da su svi problemi riješeni. Želimo proširiti perspektivu primjerima napretka, a ne zamijeniti praćenje ostalih vijesti.",
    faqTitle: "Pitanja o BrightNewsu",
    faq: [["Objavljuje li BrightNews vlastite članke?", "BrightNews je neovisan agregator vijesti. Izvorni mediji ostaju autori izvještavanja. Za cijeli članak otvorite poveznicu na izvor uz svaku priču."], ["Jesu li svi članci prevedeni?", "Ne. Sučelje aplikacije dostupno je na više jezika, ali članci i sažeci mogu ostati na jeziku izvora. Filtrima jezika, države i teme pronađite sadržaj koji vas zanima."], ["Mogu li čitati na mobitelu?", "Da. BrightNews radi u internetskom pregledniku, a dostupan je i kao Android aplikacija. Priče možete pregledavati i spremiti za kasnije."]],
    footer: "Neovisan projekt za uravnoteženiji pogled na vijesti.",
  },
  {
    locale: "sr", name: "Srpski", path: "/pozitivne-vesti", heading: "Pozitivne vesti iz celog sveta",
    description: "Pronađite pozitivne vesti i dobre priče uz BrightNews. Pratite napredak u nauci, zdravlju, prirodi i zajednici, uz linkove ka izvornim člancima.",
    open: "Čitajte vesti", android: "Preuzmite Android aplikaciju", languages: "Čitajte na svom jeziku",
    intro: "Uravnotežen pogled na svet uključuje i ono što se menja nabolje. BrightNews okuplja konstruktivne vesti različitih medija kako biste lakše pronašli dobre vesti, inspirativne priče i primere stvarnog napretka.",
    topicsTitle: "Dobre vesti koje vredi pratiti",
    topics: ["Nauka i zdravlje: otkrića, lečenje i istraživanja koja mogu poboljšati život.", "Priroda i planeta: zaštita životne sredine, obnova prirode i praktična održiva rešenja.", "Ljudi i zajednica: solidarnost, lokalne inicijative i uspesi koji pomažu drugima.", "Tehnologija i inovacije: korisne ideje i alati za rešavanje stvarnih problema."],
    selectionTitle: "Kako biramo vesti",
    selection: "BrightNews prikuplja članke putem RSS izvora i novinskih API-ja, uklanja duplikate i koristi tematske filtere i veštačku inteligenciju za prepoznavanje konstruktivnih priča. Postupak može da pogreši. Svaki sažetak vodi ka izvornom članku, gde možete proveriti detalje i kontekst.",
    balance: "Pozitivne vesti ne znače zanemarivanje teških događaja niti tvrdnju da su svi problemi rešeni. Želimo da proširimo perspektivu primerima napretka, a ne da zamenimo praćenje ostalih vesti.",
    faqTitle: "Pitanja o BrightNewsu",
    faq: [["Da li BrightNews piše sopstvene članke?", "BrightNews je nezavisan agregator vesti. Izvorni mediji ostaju autori izveštavanja. Za ceo članak otvorite link ka izvoru uz svaku priču."], ["Da li su svi članci prevedeni?", "Ne. Interfejs aplikacije dostupan je na više jezika, ali članci i sažeci mogu ostati na jeziku izvora. Filterima jezika, države i teme pronađite sadržaj koji vas zanima."], ["Mogu li da čitam na telefonu?", "Da. BrightNews radi u internet pregledaču, a dostupan je i kao Android aplikacija. Priče možete pregledati i sačuvati za kasnije."]],
    footer: "Nezavisan projekat za uravnoteženiji pogled na vesti.",
  },
  {
    locale: "bs", name: "Bosanski", path: "/bs/pozitivne-vijesti", heading: "Pozitivne vijesti iz cijelog svijeta",
    description: "Pronađite pozitivne vijesti i dobre priče uz BrightNews. Pratite napredak u nauci, zdravlju, prirodi i zajednici, uz linkove na izvorne članke.",
    open: "Čitajte vijesti", android: "Preuzmite Android aplikaciju", languages: "Čitajte na svom jeziku",
    intro: "Uravnotežen pogled na svijet obuhvata i promjene nabolje. BrightNews okuplja konstruktivne vijesti različitih medija kako biste jednostavnije pronašli dobre vijesti, inspirativne priče i primjere stvarnog napretka.",
    topicsTitle: "Dobre vijesti koje vrijedi pratiti",
    topics: ["Nauka i zdravlje: otkrića, liječenje i istraživanja koja mogu poboljšati život.", "Priroda i planeta: zaštita okoliša, obnova prirode i praktična održiva rješenja.", "Ljudi i zajednica: solidarnost, lokalne inicijative i uspjesi koji pomažu drugima.", "Tehnologija i inovacije: korisne ideje i alati za rješavanje stvarnih problema."],
    selectionTitle: "Kako biramo vijesti",
    selection: "BrightNews prikuplja članke putem RSS izvora i novinskih API-ja, uklanja duplikate te koristi tematske filtere i pomoć umjetne inteligencije za prepoznavanje konstruktivnih priča. Postupak može pogriješiti. Svaki sažetak vodi na izvorni članak, gdje možete provjeriti detalje i kontekst.",
    balance: "Pozitivne vijesti ne znače zanemarivanje teških događaja niti tvrdnju da su svi problemi riješeni. Želimo dopuniti sliku svijeta primjerima napretka, a ne zamijeniti praćenje ostalih vijesti.",
    faqTitle: "Pitanja o BrightNewsu",
    faq: [["Da li BrightNews piše vlastite članke?", "BrightNews je nezavisan agregator vijesti. Izvorni mediji ostaju autori izvještavanja. Za cijeli članak otvorite link na izvor uz svaku priču."], ["Jesu li svi članci prevedeni?", "Ne. Interfejs aplikacije dostupan je na više jezika, ali članci i sažeci mogu ostati na jeziku izvora. Filterima jezika, države i teme pronađite sadržaj koji vas zanima."], ["Mogu li čitati na mobitelu?", "Da. BrightNews radi u internetskom pregledniku, a dostupan je i kao Android aplikacija. Priče možete pregledati i sačuvati za kasnije."]],
    footer: "Nezavisan projekt za uravnoteženiji pogled na vijesti.",
  },
  {
    locale: "sl", name: "Slovenščina", path: "/pozitivne-novice", heading: "Pozitivne novice z vsega sveta",
    description: "Odkrijte pozitivne novice in dobre zgodbe z BrightNews. Spremljajte napredek v znanosti, zdravju, naravi in skupnosti s povezavami do izvirnih člankov.",
    open: "Preberite novice", android: "Prenesite aplikacijo za Android", languages: "Berite v svojem jeziku",
    intro: "Uravnotežen pogled na svet vključuje tudi spremembe na bolje. BrightNews združuje konstruktivne novice različnih medijev, da lažje odkrijete dobre novice, navdihujoče zgodbe in primere resničnega napredka.",
    topicsTitle: "Dobre novice, ki jih je vredno spremljati",
    topics: ["Znanost in zdravje: odkritja, zdravljenje in raziskave, ki lahko izboljšajo življenje.", "Narava in planet: varstvo okolja, obnova narave in praktične trajnostne rešitve.", "Ljudje in skupnost: solidarnost, lokalne pobude in dosežki, ki pomagajo drugim.", "Tehnologija in inovacije: uporabne ideje in orodja za reševanje resničnih težav."],
    selectionTitle: "Kako izbiramo novice",
    selection: "BrightNews zbira članke prek virov RSS in novičarskih API-jev, odstranjuje podvojene objave ter uporablja tematske filtre in pomoč umetne inteligence za prepoznavanje konstruktivnih zgodb. Postopek se lahko zmoti. Vsak povzetek vodi do izvirnega članka, kjer lahko preverite podrobnosti in kontekst.",
    balance: "Pozitivne novice ne pomenijo prezrtja težkih dogodkov ali trditve, da so vse težave rešene. Želimo dodati pogled na napredek, ne pa nadomestiti širšega spremljanja novic.",
    faqTitle: "Vprašanja o BrightNews",
    faq: [["Ali BrightNews piše lastne članke?", "BrightNews je neodvisen zbiralnik novic. Izvirni mediji ostajajo avtorji poročanja. Celoten članek preberete prek povezave do vira ob vsaki zgodbi."], ["Ali so vsi članki prevedeni?", "Ne. Vmesnik aplikacije je na voljo v več jezikih, članki in povzetki pa lahko ostanejo v jeziku vira. S filtri za jezik, državo in temo poiščite vsebine, ki vas zanimajo."], ["Ali lahko berem na telefonu?", "Da. BrightNews deluje v spletnem brskalniku in je na voljo tudi kot aplikacija za Android. Zgodbe lahko pregledujete in shranite za pozneje."]],
    footer: "Neodvisen projekt za bolj uravnotežen pogled na novice.",
  },
  {
    locale: "de", name: "Deutsch", path: "/positive-nachrichten", heading: "Positive Nachrichten aus aller Welt",
    description: "Entdecken Sie gute Nachrichten mit BrightNews: Fortschritte in Wissenschaft, Gesundheit, Natur und Gesellschaft, mit Links zu den Originalberichten.",
    open: "Nachrichten lesen", android: "Android-App herunterladen", languages: "In Ihrer Sprache lesen",
    intro: "Zu einem ausgewogenen Weltbild gehört auch das, was sich zum Besseren verändert. BrightNews bündelt konstruktive Berichte verschiedener Medien, damit Sie gute Nachrichten, ermutigende Geschichten und konkrete Fortschritte leichter finden.",
    topicsTitle: "Gute Nachrichten, die einen Blick verdienen",
    topics: ["Wissenschaft und Gesundheit: Entdeckungen, Behandlungen und Forschung, die das Leben verbessern können.", "Natur und Umwelt: Artenschutz, Renaturierung und praktische Lösungen für Umweltprobleme.", "Menschen und Gemeinschaft: Hilfsbereitschaft, lokale Initiativen und Erfolge, die anderen zugutekommen.", "Technologie und Innovation: nützliche Ideen und Werkzeuge für reale Herausforderungen."],
    selectionTitle: "So wählen wir Nachrichten aus",
    selection: "BrightNews sammelt Artikel über RSS-Feeds und Nachrichten-APIs, entfernt Duplikate und nutzt Themenfilter sowie KI-gestützte Prüfung, um konstruktive Geschichten zu erkennen. Dabei können Fehler entstehen. Jede Zusammenfassung verlinkt auf den Originalbericht, damit Sie Details und Zusammenhänge selbst prüfen können.",
    balance: "Positive Nachrichten bedeuten nicht, schwierige Ereignisse zu ignorieren oder alle Probleme für gelöst zu erklären. Wir möchten die Berichterstattung um Beispiele für Fortschritt ergänzen, nicht die allgemeine Nachrichtenlektüre ersetzen.",
    faqTitle: "Fragen zu BrightNews",
    faq: [["Verfasst BrightNews eigene Artikel?", "BrightNews ist ein unabhängiger Nachrichtenaggregator. Die ursprünglichen Medien bleiben die Quellen der Berichte. Über den Quellenlink einer Geschichte gelangen Sie zum vollständigen Artikel."], ["Sind alle Artikel übersetzt?", "Nein. Die Oberfläche ist mehrsprachig, Artikel und Zusammenfassungen können jedoch in der Sprache der Quelle bleiben. Mit Sprach-, Länder- und Themenfiltern finden Sie passende Inhalte."], ["Kann ich auf dem Smartphone lesen?", "Ja. BrightNews funktioniert im Browser und ist auch als Android-App verfügbar. Sie können Geschichten durchstöbern und für später speichern."]],
    footer: "Ein unabhängiges Projekt für einen ausgewogeneren Blick auf die Nachrichten.",
  },
  {
    locale: "fr", name: "Français", path: "/bonnes-nouvelles", heading: "Bonnes nouvelles du monde entier",
    description: "Découvrez des actualités positives avec BrightNews : progrès en science, santé, environnement et solidarité, avec des liens vers les articles originaux.",
    open: "Lire les actualités", android: "Télécharger l’application Android", languages: "Lire dans votre langue",
    intro: "Un regard équilibré sur le monde inclut aussi ce qui s’améliore. BrightNews rassemble des actualités constructives de plusieurs médias pour vous aider à découvrir de bonnes nouvelles, des histoires inspirantes et des exemples concrets de progrès.",
    topicsTitle: "Des bonnes nouvelles à suivre",
    topics: ["Science et santé : découvertes, traitements et recherches qui peuvent améliorer la vie.", "Nature et planète : protection des espèces, restauration des milieux et solutions environnementales concrètes.", "Personnes et communautés : solidarité, initiatives locales et réussites utiles aux autres.", "Technologie et innovation : des idées et des outils utiles pour répondre à des problèmes réels."],
    selectionTitle: "Comment nous sélectionnons les articles",
    selection: "BrightNews recueille des articles via des flux RSS et des API d’actualités, supprime les doublons et utilise des filtres thématiques ainsi qu’une analyse assistée par IA pour repérer les récits constructifs. Ce processus peut se tromper. Chaque résumé renvoie à l’article original pour vous permettre de vérifier les détails et le contexte.",
    balance: "Les actualités positives ne consistent pas à ignorer les événements difficiles ni à prétendre que tous les problèmes sont résolus. Notre objectif est d’apporter une perspective complémentaire, sans remplacer une information plus générale.",
    faqTitle: "Questions sur BrightNews",
    faq: [["BrightNews rédige-t-il les articles ?", "BrightNews est un agrégateur indépendant. Les médias d’origine restent les sources des reportages. Suivez le lien de chaque histoire pour lire l’article complet."], ["Tous les articles sont-ils traduits ?", "Non. L’interface est disponible en plusieurs langues, mais les articles et les résumés peuvent rester dans la langue de leur source. Utilisez les filtres de langue, de pays et de thème pour trouver les contenus qui vous intéressent."], ["Puis-je lire sur mon téléphone ?", "Oui. BrightNews fonctionne dans un navigateur et existe aussi en application Android. Vous pouvez parcourir les histoires et les enregistrer pour plus tard."]],
    footer: "Un projet indépendant pour un regard plus équilibré sur l’actualité.",
  },
  {
    locale: "pt", name: "Português", path: "/noticias-positivas", heading: "Notícias positivas do mundo inteiro",
    description: "Descubra boas notícias com o BrightNews: avanços em ciência, saúde, meio ambiente e comunidades, com links para as reportagens originais.",
    open: "Ler notícias", android: "Baixar o aplicativo Android", languages: "Leia no seu idioma",
    intro: "Uma visão equilibrada do mundo também inclui o que está melhorando. O BrightNews reúne notícias construtivas de diferentes veículos para ajudar você a encontrar boas notícias, histórias inspiradoras e exemplos concretos de progresso.",
    topicsTitle: "Boas notícias que vale a pena acompanhar",
    topics: ["Ciência e saúde: descobertas, tratamentos e pesquisas que podem melhorar a vida.", "Natureza e planeta: conservação, recuperação ambiental e soluções sustentáveis na prática.", "Pessoas e comunidades: solidariedade, iniciativas locais e conquistas que ajudam outras pessoas.", "Tecnologia e inovação: ideias e ferramentas úteis para resolver problemas reais."],
    selectionTitle: "Como selecionamos as notícias",
    selection: "O BrightNews coleta artigos por feeds RSS e APIs de notícias, remove duplicatas e usa filtros por tema e análise assistida por IA para identificar histórias construtivas. Esse processo pode cometer erros. Cada resumo tem um link para a reportagem original, permitindo conferir os detalhes e o contexto.",
    balance: "Notícias positivas não significam ignorar acontecimentos difíceis nem afirmar que todos os problemas foram resolvidos. Queremos acrescentar perspectiva com exemplos de progresso, sem substituir o acompanhamento mais amplo das notícias.",
    faqTitle: "Perguntas sobre o BrightNews",
    faq: [["O BrightNews escreve os artigos?", "O BrightNews é um agregador independente. Os veículos originais continuam sendo as fontes das reportagens. Acesse o link da fonte de cada história para ler o artigo completo."], ["Todos os artigos são traduzidos?", "Não. A interface está disponível em vários idiomas, mas os artigos e resumos podem permanecer no idioma da fonte. Use os filtros de idioma, país e tema para encontrar conteúdos relevantes."], ["Posso ler no celular?", "Sim. O BrightNews funciona no navegador e também está disponível como aplicativo Android. Você pode explorar histórias e salvá-las para ler depois."]],
    footer: "Um projeto independente para uma visão mais equilibrada das notícias.",
  },
  {
    locale: "ja", name: "日本語", path: "/ja/positive-news", heading: "世界の明るいニュース",
    description: "BrightNewsで世界のポジティブなニュースを見つけましょう。科学、健康、自然、地域社会の前向きな変化を、元の記事へのリンクとともに紹介します。",
    open: "ニュースを読む", android: "Androidアプリを入手", languages: "言語を選ぶ",
    intro: "世界をバランスよく知るには、良い方向への変化にも目を向けることが大切です。BrightNewsは複数のメディアから建設的なニュースを集め、明るい話題や心温まるエピソード、具体的な進歩を見つけやすくします。",
    topicsTitle: "注目したい前向きなニュース",
    topics: ["科学と健康：暮らしを良くする可能性のある発見、治療、研究。", "自然と地球：生き物の保護、自然環境の再生、実践的な環境対策。", "人と地域社会：助け合い、地域の取り組み、人の役に立つ成果。", "技術とイノベーション：現実の課題に向き合う便利なアイデアや道具。"],
    selectionTitle: "ニュースの選び方",
    selection: "BrightNewsはRSSフィードやニュースAPIから記事を集め、重複を取り除き、テーマ別フィルターとAIによる確認を用いて建設的な話題を選びます。この仕組みは誤ることもあります。各要約には元の記事へのリンクがあり、詳細や背景を自分で確認できます。",
    balance: "明るいニュースを読むことは、深刻な出来事を無視したり、すべての問題が解決したと考えたりすることではありません。幅広い報道に代わるものではなく、進歩の実例を通じて新たな視点を加えることを目指しています。",
    faqTitle: "BrightNewsについての質問",
    faq: [["BrightNewsが記事を書いているのですか？", "BrightNewsは独立したニュース集約サービスです。報道の発信元はそれぞれのメディアです。全文は各ニュースに付いている出典リンクからお読みください。"], ["すべての記事が翻訳されていますか？", "いいえ。アプリの画面は複数の言語に対応していますが、記事や要約は元の言語のままの場合があります。言語、国、テーマのフィルターで関心のあるニュースを探せます。"], ["スマートフォンでも読めますか？", "はい。BrightNewsはブラウザーで利用でき、Androidアプリもあります。ニュースを閲覧し、後で読むために保存できます。"]],
    footer: "ニュースをよりバランスよく見るための独立したプロジェクト。",
  },
];

export const LOCALIZED_SEO_PAGES = pages.map(page => ({
  ...page,
  title: `${page.heading} | BrightNews`,
  regionCode: "world",
  storyFilter: "newest",
}));

export const getLanguageAlternates = siteUrl => [
  ...LOCALIZED_SEO_PAGES.map(page => ({ language: page.locale, url: `${siteUrl}${page.path}` })),
  { language: "x-default", url: `${siteUrl}/positive-news` },
];

export const getLocalizedPageSchema = (page, siteUrl) => ({
  "@context": "https://schema.org", "@type": "WebPage", name: page.title,
  description: page.description, url: `${siteUrl}${page.path}`, inLanguage: page.locale,
  isPartOf: { "@type": "WebSite", name: "BrightNews", url: siteUrl },
});
