export const SITE_URL = import.meta.env?.VITE_SITE_URL || "https://brightnews.app";
export const GOOGLE_PLAY_URL = "https://play.google.com/store/apps/details?id=com.mateomustapic.brightnews";

const countryRoute = ({
  slug,
  country,
  regionCode,
  adjective,
}) => ({
  path: `/positive-news/${slug}`,
  title: `Positive News ${country} | Good News and Uplifting Stories`,
  heading: `Positive News ${country}`,
  eyebrow: `${country} edition`,
  description: `Positive and constructive news from ${country}, including health, science, nature, innovation and community stories.`,
  keywords: `positive news ${country}, good news ${country}, uplifting ${adjective} news`,
  intro: [
    `Find positive news from ${country} in one calmer place, focused on constructive updates instead of outrage and doomscrolling.`,
    `This roundup highlights source-linked stories about progress, health, science, nature, innovation, community and everyday people making things better.`,
  ],
  regionCode,
  storyFilter: "newest",
});

const usaRoute = ({
  path,
  title,
  heading,
  eyebrow,
  description,
  keywords,
  intro,
  categoryId = "all",
  storyFilter = "newest",
}) => ({
  path,
  title,
  heading,
  eyebrow,
  description,
  keywords,
  intro,
  regionCode: "us",
  categoryId,
  storyFilter,
});

const topicalRoute = ({
  path,
  title,
  heading,
  eyebrow,
  description,
  keywords,
  intro,
  categoryId = "all",
  storyFilter = "newest",
}) => ({
  path,
  title,
  heading,
  eyebrow,
  description,
  keywords,
  intro,
  regionCode: "world",
  categoryId,
  storyFilter,
});

export const SEO_ROUTES = [
  {
    path: "/positive-news",
    title: "Positive News | Good News and Uplifting Stories Worldwide",
    heading: "Positive News",
    eyebrow: "Worldwide positive news",
    description: "Read positive news, good news and uplifting stories from around the world, updated regularly with source-linked constructive stories.",
    keywords: "positive news, good news, uplifting news, worldwide positive news, positive stories, constructive news",
    intro: [
      "Positive news helps balance the daily news cycle with stories about progress, kindness, science, health, nature, innovation and community action.",
      "This page collects source-linked positive news from around the world, so you can stay informed without spending all your time in negative headlines.",
      "Use it as a daily place for good news, uplifting stories and constructive current events from multiple countries and topics.",
    ],
    regionCode: "world",
    storyFilter: "newest",
  },
  {
    path: "/positive-news-today",
    title: "Positive News Today | Good News From Around the World",
    heading: "Positive News Today",
    eyebrow: "Updated daily",
    description: "Read positive news today, including uplifting stories, good news and constructive current events from around the world.",
    keywords: "positive news today, good news today, uplifting news today, positive current events, good news in the world",
    intro: [
      "Looking for positive news today? This roundup surfaces fresh good news and uplifting stories from around the world.",
      "The focus is on constructive current events: health progress, scientific discovery, nature recovery, innovation, community action and people helping people.",
    ],
    regionCode: "world",
    storyFilter: "newest",
  },
  {
    path: "/good-news-today",
    title: "Good News Today | Positive News and Uplifting Stories",
    heading: "Good News Today",
    eyebrow: "Today's good news",
    description: "Read good news today with positive stories, uplifting news and constructive current events from around the world.",
    keywords: "good news today, positive news today, uplifting news today, good news stories today, positive stories today",
    intro: [
      "Good news today should be easy to find. This page brings together fresh positive stories and constructive current events from source-linked articles.",
      "Read uplifting news about people, science, health, nature, innovation and communities without getting stuck in outrage-driven headlines.",
    ],
    regionCode: "world",
    storyFilter: "newest",
  },
  {
    path: "/worldwide-positive-news",
    title: "Worldwide Positive News | Good News Around the World",
    heading: "Worldwide Positive News",
    eyebrow: "Global roundup",
    description: "Worldwide positive news from multiple countries, with uplifting stories about progress, people, nature, health, science and innovation.",
    keywords: "worldwide positive news, good news around the world, positive world news, uplifting world news, good news in the world",
    intro: [
      "Worldwide positive news brings together constructive stories from different countries and regions, not just one local news cycle.",
      "This page is built for readers who want good news around the world: progress stories, hopeful discoveries, community wins and real source-linked updates.",
    ],
    regionCode: "world",
    storyFilter: "newest",
  },
  {
    path: "/positive-world-news",
    title: "Positive World News | Good News Around the World",
    heading: "Positive World News",
    eyebrow: "World good news",
    description: "Positive world news and uplifting global stories about progress, communities, health, science, nature and innovation.",
    keywords: "positive world news, positive news around the world, good world news, uplifting world news, positive world news today",
    intro: [
      "Positive world news highlights constructive stories from different regions instead of focusing only on crisis and conflict.",
      "This roundup is built for readers looking for good news around the world, including progress stories, health updates, discovery, nature recovery and people helping people.",
    ],
    regionCode: "world",
    storyFilter: "newest",
  },
  topicalRoute({
    path: "/positive-world-news-today",
    title: "Positive World News Today | Uplifting Global Stories",
    heading: "Positive World News Today",
    eyebrow: "Today's world roundup",
    description: "Positive world news today with uplifting global stories about progress, communities, health, science, nature and innovation.",
    keywords: "positive world news today, positive news around the world today, good world news today, uplifting world news today",
    intro: [
      "Positive world news today gives readers a direct way to find constructive global stories without starting from crisis-heavy headlines.",
      "This roundup focuses on hopeful current events from multiple countries, including progress in health, science, nature, education, communities and innovation.",
    ],
  }),
  {
    path: "/good-news-in-the-world",
    title: "Good News in the World | Positive Stories Worldwide",
    heading: "Good News in the World",
    eyebrow: "Global good news",
    description: "Good news in the world, including positive stories about people, science, health, nature, communities and meaningful progress.",
    keywords: "good news in the world, good news around the world, positive stories worldwide, uplifting world stories",
    intro: [
      "There is still good news in the world. This page collects constructive stories that often get buried under crisis-driven headlines.",
      "Read about useful discoveries, community projects, health wins, conservation progress and people making daily life better.",
    ],
    regionCode: "world",
    storyFilter: "featured",
  },
  {
    path: "/positive-current-events",
    title: "Positive Current Events | Constructive News Today",
    heading: "Positive Current Events",
    eyebrow: "Constructive updates",
    description: "Positive current events and constructive news stories about progress, discovery, health, nature, innovation and communities.",
    keywords: "positive current events, constructive current events, positive news today, good current events, uplifting current events",
    intro: [
      "Positive current events are not about ignoring reality. They are about making room for progress, solutions and constructive stories alongside the hard news.",
      "This page highlights current positive news from source-linked articles across science, health, nature, innovation and community topics.",
    ],
    regionCode: "world",
    storyFilter: "newest",
  },
  {
    path: "/good-news-only",
    title: "Good News Only | Positive and Uplifting News",
    heading: "Good News Only",
    eyebrow: "No doomscrolling",
    description: "A good-news-only feed with positive, uplifting and constructive stories from around the world.",
    keywords: "good news only, positive news only, uplifting news, good news feed, positive stories",
    intro: [
      "Good news only means a calmer reading experience focused on constructive, uplifting and useful stories.",
      "The feed still links to original sources, but filters toward stories about progress, kindness, health, science, nature and innovation.",
    ],
    regionCode: "world",
    storyFilter: "featured",
  },
  {
    path: "/wholesome-news",
    title: "Wholesome News | Uplifting Stories and Good News",
    heading: "Wholesome News",
    eyebrow: "Uplifting stories",
    description: "Wholesome news and uplifting stories about people, kindness, progress, communities and good things happening in the world.",
    keywords: "wholesome news, uplifting stories, good news, positive stories, feel good news",
    intro: [
      "Wholesome news is for moments when you want to read about people helping, communities improving and good things happening in the world.",
      "This roundup combines uplifting stories with constructive news across people, health, science, nature and innovation.",
    ],
    regionCode: "world",
    categoryId: "Community",
    storyFilter: "top",
  },
  {
    path: "/positive-stories",
    title: "Positive Stories | Uplifting Stories From Real Sources",
    heading: "Positive Stories",
    eyebrow: "Source-linked stories",
    description: "Positive stories and uplifting news from real sources, focused on progress, kindness, discovery, health, nature and innovation.",
    keywords: "positive stories, uplifting stories, positive news stories, good news stories, inspiring stories",
    intro: [
      "Positive stories can change the way daily news feels. This page gathers source-linked stories about useful progress and people doing good work.",
      "Browse uplifting stories from around the world without losing the link back to the original reporting.",
    ],
    regionCode: "world",
    storyFilter: "top",
  },
  topicalRoute({
    path: "/positive-news-stories",
    title: "Positive News Stories | Good News and Uplifting Updates",
    heading: "Positive News Stories",
    eyebrow: "Stories worth reading",
    description: "Positive news stories from credible sources, focused on good news, uplifting updates and constructive progress around the world.",
    keywords: "positive news stories, good news stories, uplifting news stories, positive stories today, inspiring news stories",
    intro: [
      "Positive news stories make it easier to notice useful progress, human kindness, scientific discovery and community improvements.",
      "BrightNews keeps the original source link attached, so each uplifting story can be explored in context instead of becoming another unsourced social post.",
    ],
    storyFilter: "top",
  }),
  topicalRoute({
    path: "/positive-news-of-the-day",
    title: "Positive News of the Day | Good News Worth Reading",
    heading: "Positive News of the Day",
    eyebrow: "Daily good news",
    description: "Positive news of the day with uplifting stories, good news and constructive current events from around the world.",
    keywords: "positive news of the day, positive news for the day, good news of the day, uplifting news of the day",
    intro: [
      "Positive news of the day is for readers who want one calmer place to catch up on constructive stories.",
      "The page highlights good news from the latest BrightNews feed, with source-linked summaries across people, health, science, nature, innovation and communities.",
    ],
    storyFilter: "featured",
  }),
  topicalRoute({
    path: "/uplifting-news-today",
    title: "Uplifting News Today | Positive Stories and Good News",
    heading: "Uplifting News Today",
    eyebrow: "Today's uplifting news",
    description: "Uplifting news today with positive stories, good news and constructive current events from credible sources.",
    keywords: "uplifting news today, positive uplifting news today, good uplifting news, uplifting stories today",
    intro: [
      "Uplifting news today should still be credible, timely and useful. BrightNews focuses on source-linked stories instead of vague feel-good posts.",
      "Browse constructive current events and positive stories about people making progress, science moving forward and communities improving daily life.",
    ],
    storyFilter: "top",
  }),
  {
    path: "/good-news-this-week",
    title: "Good News This Week | Positive Stories and Uplifting News",
    heading: "Good News This Week",
    eyebrow: "Weekly roundup",
    description: "A calm roundup of good news, progress stories and constructive updates from the latest BrightNews feed.",
    keywords: "good news this week, positive news this week, positive stories this week, uplifting stories 2026",
    intro: [
      "Good news this week gives you a quick way to catch up on positive stories without scanning every negative headline first.",
      "This weekly-style roundup emphasizes constructive news, meaningful progress and uplifting stories from the latest feed.",
    ],
    regionCode: "world",
    storyFilter: "featured",
  },
  {
    path: "/uplifting-stories",
    title: "Uplifting Stories From Around the World | Positive News",
    heading: "Uplifting Stories",
    eyebrow: "Positive story roundup",
    description: "Discover positive stories about people, health, science, nature, innovation and meaningful progress.",
    keywords: "uplifting stories, positive stories, constructive news, feel good news, inspiring stories",
    intro: [
      "Uplifting stories are the part of the news cycle that can remind readers that progress, kindness and discovery are happening too.",
      "This page collects positive stories from real sources across people, health, science, nature, innovation and meaningful progress.",
    ],
    regionCode: "world",
    storyFilter: "top",
  },
  {
    path: "/uplifting-news",
    title: "Uplifting News Today | Positive Stories From Around the World",
    heading: "Uplifting News",
    eyebrow: "Positive updates",
    description: "Uplifting news today from around the world, with positive stories about people, progress, health, science, nature and communities.",
    keywords: "uplifting news, uplifting news today, positive uplifting news, uplifting stories, good news today",
    intro: [
      "Uplifting news gives readers a calmer way to stay informed, with stories about progress, kindness, discovery and people making daily life better.",
      "This page gathers source-linked positive news from around the world and filters toward constructive updates instead of doomscrolling.",
    ],
    regionCode: "world",
    storyFilter: "top",
  },
  topicalRoute({
    path: "/good-news-about-the-environment",
    title: "Good News About the Environment | Positive Nature News",
    heading: "Good News About the Environment",
    eyebrow: "Nature and climate solutions",
    description: "Good news about the environment, including positive nature stories, conservation progress and constructive climate solutions.",
    keywords: "good news about the environment, positive environmental news, good climate news, positive nature news, conservation good news",
    intro: [
      "Good news about the environment is not about pretending problems do not exist. It is about tracking conservation wins, restoration work and practical climate solutions.",
      "This page collects positive environmental news from source-linked stories about nature recovery, community action, cleaner technology and measurable progress.",
    ],
    categoryId: "Environment",
    storyFilter: "featured",
  }),
  countryRoute({ slug: "usa", country: "USA", regionCode: "us", adjective: "American" }),
  usaRoute({
    path: "/positive-news/usa/today",
    title: "Positive News Today USA | Good News America",
    heading: "Positive News Today USA",
    eyebrow: "USA daily roundup",
    description: "Fresh positive news from the USA today, with uplifting American stories about progress, people, health, science and communities.",
    keywords: "positive news today USA, good news today USA, uplifting news America, positive American news today",
    intro: [
      "Read positive news today from the USA, focused on constructive stories instead of outrage-driven headlines.",
      "This page highlights uplifting American stories about communities, health, science, nature, innovation and people making progress.",
    ],
  }),
  usaRoute({
    path: "/good-news/usa/this-week",
    title: "Good News USA This Week | BrightNews",
    heading: "Good News USA This Week",
    eyebrow: "USA weekly roundup",
    description: "A weekly roundup of good news from the USA, focused on constructive American stories and hopeful updates.",
    keywords: "good news USA this week, positive stories America this week, uplifting American stories",
    storyFilter: "featured",
  }),
  usaRoute({
    path: "/uplifting-stories/usa",
    title: "Uplifting Stories USA | BrightNews",
    heading: "Uplifting Stories USA",
    eyebrow: "American stories",
    description: "Uplifting stories from the USA about kindness, progress, discovery, resilience and everyday people making life brighter.",
    keywords: "uplifting stories USA, uplifting American stories, feel good news USA, positive stories America",
    storyFilter: "top",
  }),
  usaRoute({
    path: "/positive-news/usa/health",
    title: "Positive Health News USA | BrightNews",
    heading: "Positive Health News USA",
    eyebrow: "USA health",
    description: "Positive health news from the USA, including medical progress, wellbeing, research and constructive healthcare stories.",
    keywords: "positive health news USA, good health news America, uplifting healthcare news USA",
    categoryId: "Health",
  }),
  usaRoute({
    path: "/positive-news/usa/science",
    title: "Positive Science News USA | BrightNews",
    heading: "Positive Science News USA",
    eyebrow: "USA science",
    description: "Positive science news from the USA, including research breakthroughs, discovery, education and innovation stories.",
    keywords: "positive science news USA, good science news America, uplifting science stories USA",
    categoryId: "Science",
  }),
  usaRoute({
    path: "/positive-news/usa/environment",
    title: "Positive Environment News USA | BrightNews",
    heading: "Positive Environment News USA",
    eyebrow: "USA environment",
    description: "Positive environmental news from the USA, including nature, conservation, climate progress and community action.",
    keywords: "positive environment news USA, good climate news America, conservation news USA, uplifting nature stories USA",
    categoryId: "Environment",
  }),
  countryRoute({ slug: "uk", country: "UK", regionCode: "uk", adjective: "British" }),
  countryRoute({ slug: "croatia", country: "Croatia", regionCode: "hr", adjective: "Croatian" }),
  countryRoute({ slug: "slovenia", country: "Slovenia", regionCode: "si", adjective: "Slovenian" }),
  countryRoute({ slug: "serbia", country: "Serbia", regionCode: "rs", adjective: "Serbian" }),
  countryRoute({ slug: "bosnia-and-herzegovina", country: "Bosnia and Herzegovina", regionCode: "ba", adjective: "Bosnian" }),
  countryRoute({ slug: "germany", country: "Germany", regionCode: "de", adjective: "German" }),
  countryRoute({ slug: "france", country: "France", regionCode: "fr", adjective: "French" }),
  countryRoute({ slug: "canada", country: "Canada", regionCode: "ca", adjective: "Canadian" }),
  countryRoute({ slug: "japan", country: "Japan", regionCode: "jp", adjective: "Japanese" }),
  countryRoute({ slug: "malaysia", country: "Malaysia", regionCode: "my", adjective: "Malaysian" }),
  countryRoute({ slug: "australia", country: "Australia", regionCode: "au", adjective: "Australian" }),
  countryRoute({ slug: "brazil", country: "Brazil", regionCode: "br", adjective: "Brazilian" }),
  countryRoute({ slug: "india", country: "India", regionCode: "in", adjective: "Indian" }),
];

export const getSeoRoute = pathname => {
  const normalizedPathname = String(pathname || "/").replace(/\/+$/, "") || "/";
  return SEO_ROUTES.find(route => route.path === normalizedPathname);
};

export const getSeoRouteLinks = () => SEO_ROUTES.map(route => ({
  ...route,
  url: `${SITE_URL}${route.path}`,
}));
